<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type, Authorization");
header("Content-Type: application/json; charset=UTF-8");

require "classes/Question.php";

function generateQuestions($difficulty) {
    switch ($difficulty) {
        case "veryeasy" :
            $dataQ = [
                ["Quel est le nom du quiz?", ["QuestionsPourUnChampignon", "The Impossible Quiz", "Projet QCM"], "QuestionsPourUnChampignon"],
                ["Où se situe la Tour Eiffel?", ["Washington", "Paris", "Sydney"], "Paris"],
                ["Le Tigre est-il un animal en voie de disparition?", ["Oui", "Non"], "Oui"],
                ["Quel est la plus haute montagne?", ["Mont Blanc", "Everest", "Mont Fuji"], "Everest"],
                ["1+1 = ?", ["2", "3", "67357"], "2"],
                ["De combien de couleurs est constitué l'arc-en-ciel?", ["3", "2", "6"], "6"],
                ["Quel est le rôle d'un tournevis?", ["Serrer et desserrer des vis", "Planter des clous"], "Serrer et desserrer des vis"],
                ["Trouver le nombre suivant dans la suite de nombres : 1, 2, 3, ?", ["5", "4"], "4"],
                ["Cette question permet-elle de gagner une vie?", ["Oui", "Non"], "Non"],
                ["Quel est la ville la plus peuplée parmi les réponses suivantes?", ["Paris", "Tokyo", "Berlin"], "Tokyo"],
                ["Cette phrase ne contient pas sept mots.", ["Si!", "Non"], "Si!"],
                ["Une pizza est-elle un sandwich?", ["Oui", "Non"], "Non"],
                ["Quel animal miaule?", ["Oiseau", "Chien", "Chat"], "Chat"],
                ["Quel couleur est le soleil vu de la Terre?", ["Jaune", "Bleu", "Rouge"], "Jaune"],
                ["Quel organe du corps humain sert pour respirer?", ["Estomac", "Coeur", "Poumons"], "Poumons"],
                ["Sur quel continent se trouve la France?", ["Océanie", "Asie", "Europe"], "Europe"],
                ["Combien de jours dans une semaine?", ["7", "6"], "7"],
                ["Où se trouve le cerveau?", ["Dans l'abdomen", "Dans la tête"], "Dans la tête"],
                ["Combien d'heures dans une journée?", ["27", "22", "24"], "24"],
                ["Quel est la 20ème lettre de l'alphabet?", ["C", "O", "T"], "T"]
            ];
            break;
        case "easy" :
            $dataQ = [
                ["6x7 = ?", ["47", "43", "41", "42"], "42"],
                ["Où se situe l'Empire State Building?", ["New York", "Seattle", "Los Angeles", "Washington"], "New York"],
                ["En quel année a commencé la 1ère Guerre Mondiale?", ["1918", "1915", "1914", "1912"], "1914"],
                ["Quel est l'intrus?", ["Courgette", "Citrouille", "Maïs", "Tomate"], "Tomate"],
                ["Quel planète est la plus proche du Soleil?", ["Vénus", "Jupiter", "Mercure", "La Terre"], "Mercure"],
                ["Un omnivore mange :", ["Des hommes", "Des plantes et de la viande", "De la viande", "Des OVNIS"], "Des plantes et de la viande"],
                ["En quel année a eu lieu la Révolution Française?", ["1784", "1789", "1788", "1798"], "1789"],
                ["Trouver le nombre suivant dans la suite de nombres : 64, 128, 256, 512, ?", ["1024", "1026", "1025", "1021"], "1024"],
                ["Quel est le carré de 25?", ["3", "9", "5", "25"], "5"],
                ["Qui a peint la Joconde?", ["Léonard de Vinci", "Pablo Picasso", "Rembrandt", "Le Caravage"], "Léonard de Vinci"],
                ["Quel pays n'appartient pas à l'Union Européenne?", ["Espagne", "Suisse", "France", "Bulgarie"], "Suisse"],
                ["Quel est le plus grand pays au monde?", ["Chine", "Etats-Unis", "Portugal", "Russie"], "Russie"],
                ["Quel est la plus grande lune du Système Solaire?", ["Io", "Titan", "La Lune", "Ganymède"], "Ganymède"],
                ["Combien de côtés possède un octogone?", ["8", "7", "5", "10"], "8"],
                ["Combien de touches sur un piano standard?", ["83", "86", "88", "90"], "88"],
                ["La comète Halley reviens tous les :", ["80 ans", "3000 ans", "76 ans", "6 mois"], "76 ans"],
                ["Combien d'os dans un squelette adulte?", ["204", "202", "206", "208"], "206"],
                ["Où se trouve l'humérus?", ["Dans la jambe", "Dans le bras", "Dans l'abdomen", "Dans la main"], "Dans le bras"],
                ["Quel élément chimique est représenté par 'H'?", ["Hydrogène", "Oxygène", "Hassium", "Hélium"], "Hydrogène"],
                ["Qu'est-ce qui se trouve au centre de l'atome?", ["Des électrons", "Le noyau", "Des photons", "Des quarks"], "Le noyau"]
            ];
            break;
        case "medium" :
            $dataQ = [
                ["45×3+27÷3−18 = ?", ["126", "114", "167", "222", "132"], "126"],
                ["Quel pays utilise le Yen? (¥)", ["Corée du Sud", "Chine", "Inde", "Myanmar", "Japon"], "Japon"],
                ["Cérès est :", ["Un asteroïde", "Une planète", "Une lune", "Une planète naine", "Une comète"], "Une planète naine"],
                ["Quel est la capitale de la Russie?", ["Paris", "Moscou", "Prague", "Madrid", "Copenhague"], "Moscou"],
                ["Quel planète est incliné de presque 90° sur son axe?", ["Jupiter", "Vénus", "Mercure", "Uranus", "Mars"], "Uranus"],
                ["Quel est la somme des 3 angles d'un triangle?", ["360°", "270°", "180°", "90°", "On ne peut pas additionner des angles"], "180°"],
                ["Quel est la probabilité de répondre bon à cette question si vous choisissez au hasard?", ["25%", "25%", "50%", "60%", "Euh..."], "Euh..."],
                ["Combien de chiffres après la virgule dans Pi?", ["Infini", "10 000", "100 000", "1 000 000", "10 000 000"], "Infini"],
                ["Quel est l'intrus?", ["Bhoutan", "Turkménistan", "Tonga", "Chine", "Laos"], "Tonga"],
                ["Qui a peint la Naissance de Vénus?", ["Léonard de Vinci", "Van Gogh", "Botticelli", "Hokusai", "Claude Monet"], "Botticelli"],
                ["Qu'est-ce qui contrôle la quantité de sang dans le corps?", ["Moelle osseuse", "Rate", "Amygdales", "Coeur", "Artères"], "Rate"],
                ["Quel est le plus petit pays au monde?", ["Luxembourg", "Andorre", "Vatican", "Lebanon", "Tuvalu"], "Vatican"],
                ["Quel est la plus grande étoile connu à ce jour?", ["Soleil", "Bételgeuse", "VY Canis Majoris", "R136a1", "UY Scuti"], "UY Scuti"],
                ["Combien de diagonales possède un heptagone?", ["11", "16", "12", "14", "9"], "14"],
                ["Quelle est la fréquence du 'La' standard, utilisée pour accorder les instruments dans l'orchestre?", ["400 Hz", "420 Hz", "440 Hz", "480 Hz", "450 Hz"], "440 Hz"],
                ["Combien d'éclipses solaire se produisent par an en moyenne?", ["1", "2", "3", "4", "5"], "2"],
                ["Trouver le nombre suivant dans la suite de nombres : 81, 243, 729, 2187, ?", ["6567", "6563", "6561", "6557", "6570"], "6561"],
                ["Combien de secondes dans 1 heure?", ["2400", "3200", "3600", "3800", "4200"], "3600"],
                ["Quel est la température moyenne de la Terre?", ["12 °C", "11 °C", "14 °C", "18 °C", "15 °C"], "15 °C"],
                ["Quel style de danse est associé aux claquettes?", ["Le Charleston", "Le Jazz", "Les Claquettes Américaines", "La Salsa", "Le Flamenco"], "Les Claquettes Américaines"],
                ["Quel est la langue officielle de l'Algérie?", ["Arabe", "Anglais", "Espagnol", "Français", "Italien"], "Arabe"],
                ["Qui a écrit Le Tartuffe?", ["Molière", "Victor Hugo", "Gustave Flaubert", "Emile Zola", "Jean-Paul Sartre"], "Molière"],
                ["Quel est le plus grand désert au monde?", ["Sahara", "Désert de l'Antartique", "Désert du Gobi", "Désert d'Arabie", "Désert du Kalahari"], "Désert de l'Antartique"],
                ["En quel année Neil Armstrong a marché sur la Lune?", ["1968", "1973", "1966", "1969", "1971"], "1969"],
                ["Qui a découvert la pénicilline?", ["Louis Pasteur", "Marie Curie", "Nikola Tesla", "Alexander Fleming", "Albert Einstein"], "Alexander Fleming"],
                ["Quel est le produit de 12 et 15?", ["180", "120", "225", "210", "200"], "180"],
                ["Que signifie 'guépard' en Anglais?", ["Lion", "Cheetah", "Hyena", "Guepard", "Leopard"], "Cheetah"],
                ["Dans quel état se trouve le parc de Yellowstone?", ["Colorado", "Texas", "Idaho", "Montana", "Wyoming"], "Wyoming"],
                ["Où se trouve le plus haut mont des Etats-Unis?", ["Alaska", "Colorado", "Mississipi", "Hawaï", "Arizona"], "Alaska"],
                ["Combien de fois on peut soustraire 10 de 100?", ["10", "9", "1", "11", "Autant de fois qu'on veut"], "1"],
            ];
            break;
        case "hard" :
            $dataQ = [
                ["Un homme peut-il épouser la soeur de sa veuve?", ["Oui", "Non", "Dans certains pays", "Cela dépend", "Sous certaines conditions"], "Non"],
                ["Quel est la valeur de Pi au millième près?", ["3,141", "3,142", "3,145", "3,147", "3,143"], "3,141"],
                ["Combien de mois ont 28 jours?", ["1", "2", "12", "0", "3"], "12"],
                ["Dans une course, dans quelle position êtes-vous après avoir doublé la personne en 3ème place?", ["1er", "4ème", "2ème", "3ème", "5ème"], "3ème"],
                ["Quel est la capitale de l'Australie?", ["Melbourne", "Perth", "Sydney", "Brisbane", "Canberra"], "Canberra"],
                ["Combien de temps dure une journée sur Terre?", ["23h 56m", "24h", "24h 10m", "23h 50m", "25h"], "23h 56m"],
                ["Lorsque l'on plie une feuille de papier 50 fois, quelle serait son épaisseur finale?", ["Quelques centimètres", "Quelques mètres", "La taille d'une maison", "Aussi haut que l'Everest", "Plus loin que la distance Terre-Lune"], "Plus loin que la distance Terre-Lune"],
                ["Que signifie le symbole suivant en maths? ∈", ["Union", "Si et seulement si", "Contient comme élément", "Appartient à", "Existe"], "Appartient à"],
                ["Que vaux x? 3x+5=20", ["12", "18", "5", "15", "17"], "5"],
                ["Quel est l'intrus?", ["Rouge", "Rose", "Violet", "Vert", "Bleu"], "Rose"],
                ["Combien de côtés possède un pentadécagone?", ["5", "25", "16", "15", "Cette figure n'existe pas"], "15"],
                ["Quel est la somme des angles d'un pentagone?", ["180", "360", "540", "270", "90"], "540"],
                ["Quel est le principal gaz dans l'atmosphère terrestre?", ["Oxygène", "Azote", "Ozone", "Dioxyde de carbone", "Hélium"], "Azote"],
                ["Quel élément chimique est représenté par 'K'?", ["Krypton", "Or", "Carbone", "Calcium", "Potassium"], "Potassium"],
                ["Quel est l'os le plus long du corps humain?", ["Tibia", "Humérus", "Fémur", "Radius", "Crâne"], "Fémur"],
                ["Quel phénomène naturel est mesuré par l'échelle de Richter?", ["Tornade", "Tremblement de Terre", "Tsunami", "Eruption", "Ouragan"], "Tremblement de Terre"],
                ["(1+(5x4-7)x3)+5x(60x3+5x5)-67 = ?", ["1000", "997", "1004", "1013", "998"], "998"],
                ["Quel est la différence entre le produit de 12 et 15 et la somme de 60 et 45 ?", ["72", "80", "70", "75", "77"], "75"],
                ["Dans quel pays est né le reggae?", ["Haïti", "France", "Jamaïque", "Myanmar", "Australie"], "Jamaïque"],
                ["Quel est l'échelle de mesure du volume sonore'?", ["Hertz", "Amplitude", "Décibel", "Lumens", "Centi-grade"], "Décibel"],
                ["Qui était le premier président des Etats-Unis?", ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams", "James Madison"], "George Washington"],
                ["Quel civilisation ancienne a construit les pyramides?", ["Les Romains", "Les Grecs", "Les Egyptiens", "Les Mayas", "Les Aztèques"], "Les Egyptiens"],
                ["Quel évènement a déclenché la 1ère Guerre Mondiale?", ["L'invasion de la Pologne", "Le bombardement de Pearl Harbor", "La Révolution russe", "La signature du traité de Versailles", "L'assassinat de François-Ferdinand"], "L'assassinat de François-Ferdinand"],
                ["Qu'est-ce qui a causé la course à l'espace?", ["La découverte de nouvelles ressources sur la Lune", "Le besoin d'explorer d'autres planètes", "La recherche d'une nouvelle source d'énergie", "La compétition technologique entre les États-Unis et l'Union soviétique", "Les avancées dans la navigation aérienne"], "La compétition technologique entre les États-Unis et l'Union soviétique"],
                ["Qu'est-ce qu'une clé de sol?", ["Un type de guitare", "Un terme pour désigner un morceau de musique dans le ton de sol", "Une technique de jeu au piano", "Un symbole musical qui indique la hauteur des notes sur une portée", "Un élément de notation utilisé uniquement pour la musique vocale"], "Un symbole musical qui indique la hauteur des notes sur une portée"],
                ["Quel est le symbole du pound?", ["$", "₽", "€", "¥", "£"], "£"],
                ["Qui a peint la Plage de Pourville?", ["Van Gogh", "Claude Monet", "Ludwig Knaus", "Léonard de Vinci", "Pablo Picasso"], "Claude Monet"],
                ["Quel lettre dans la langue française est la moins utilisé?", ["K", "Z", "Y", "W", "X"], "W"],
                ["Que signifie 'cheval' en espagnol?", ["Gato", "Oveja", "Pez", "Conejo", "Caballo"], "Caballo"],
                ["Quel est le principal conducteur dans les fils électriques?", ["Or", "Fer", "Cuivre", "Zinc", "Plastique"], "Cuivre"],
                ["Quel dispositif transforme l'énergie électrique en énergie lumineuse?", ["Résistance", "Condensateur", "Transistor", "Diode", "Ampoule"], "Diode"],
                ["Quelle est la principale source de nourriture pour de nombreux animaux marins dans l'océan?", ["Zooplancton", "Débris organiques", "Plantes aquatiques", "Phytoplancton", "Poisson"], "Phytoplancton"],
                ["Quel est l'impact principal du réchauffement climatique sur les océans?", ["Augmentation des niveaux de la mer", "Diminution des niveaux de salinité", "Acidification des océans", "Augmentation des courants océaniques", "Réduction des tempêtes océaniques"], "Acidification des océans"],
                ["Quel est le plus grand réseau de catacombes au monde?", ["Catacombes de Paris", "Catacombes de Rome", "Catacombes de Naples", "Catacombes de Prague", "Catacombes de Lisbonne"], "Catacombes de Naples"],
                ["Quel événement est célébré à Noël dans le christianisme?", ["La dernière Cène", "L'Ascension de Jésus", "La Pentecôte", "La naissance de Jésus", "La résurrection de Jésus"], "La naissance de Jésus"],
                ["Quel est le nom du livre sacré de l'hindouisme?", ["Les Vedas", "La Bible", "Le Tao Te Ching", "Le Coran", "La Torah"], "Les Vedas"],
                ["Quel est le jeûne sacré observé par les musulmans pendant le mois de Ramadan?", ["Seder", "Sawm", "Carême", "Yom Kippour", "Navratri"], "Sawm"],
                ["Combien de zéros dans le milliard?", ["8", "9", "12", "6", "15"], "9"],
                ["Quel est le plus petit nombre entier qui ne peut être écrit comme la somme de deux nombres premiers?", ["2", "6", "5", "4", "9"], "4"],
                ["Quel jeu de cartes est souvent considéré comme le plus populaire dans les casinos?", ["Rami", "Bridge", "Blackjack", "Poker", "Baccarat"], "Blackjack"],
                ["Quel site archéologique péruvien est souvent considéré comme une des Sept Merveilles du monde moderne?", ["Le Colisée", "Le Christ Rédempteur", "Petra", "Chichen Itza", "Machu Pichu"], "Machu Pichu"],
                ["Quel est la distance moyenne entre la Terre et le Soleil?", ["1 UA", "1,5 UA", "93 millions de kilomètres", "30 millions de kilomètres", "5 UA"], "1 UA"],
                ["Quel est la principale composante du noyau des étoiles?", ["Hydrogène", "Carbone", "Fer", "Hélium", "On ne sait pas"], "Hydrogène"],
                ["Quel est le nom de la première sonde spatiale à avoir quitté notre Système Solaire?", ["Voyager 1", "Voyager 2", "New Horizons", "Pioneer 10", "Aucune sonde n'a quitté le Système Solaire"], "Voyager 1"],
                ["Quel type de galaxies est le plus souvent trouvé dans les groupes de galaxies?", ["Lenticulaires", "Spirales", "Irrégulières", "Elliptiques", "Actions"], "Spirales"],
                ["Quel est le principal moyen utilisé pour détecter les exoplanètes?", ["L'observation directe", "Les mesures de la luminosité", "L'imagerie infrarouge", "La méthode des transits", "L'effet Doppler"], "La méthode des transits"],
                ["Combien de départements dans l'Héxagone?", ["101", "96", "18", "98", "103"], "96"],
                ["Quel partie de la plante est responsable de la photosynthèse?", ["Les fleurs", "La tige", "Les pétales", "Les feuilles", "Les racines"], "Les feuilles"],
                ["Quel est la proportion d'eau salée sur Terre?", ["90%", "80%", "50%", "97%", "99%"], "97%"],
                ["Combien de chambres possède notre coeur?", ["2", "4", "6", "1", "On n'appelle pas ça des chambres"], "4"],
            ];
            break;
        case "extreme" :
            $dataQ = [
                ["Quel est le plus grand organe du corps humain?", [], "peau"],
                ["En quel année Christophe Colomb a découvert l'Amérique?", [], "1492"],
                ["Combien de joueurs dans une équipe de football?", [], "11"],
                ["Quel est l'animal national de la France?", [], "coq"],
                ["Combien de cordes sur une guitare classique?", [], "6"],
                ["Quel pays est surnommé 'Le pays du Soleil levant'?", [], "japon"],
                ["Quel métal est le plus léger parmi les éléments courants?", [], "lithium"],
                ["Quel est le plus grand en termes de superficie : Russie ou Pluton?", [], "russie"],
                ["Dans quel pays se trouve la région du Transsibérien?", [], "russie"],
                ["Combien de points vaut un essai au rugby?", [], "5"],
                ["Quel compositeur a écrit 'Les Quatre Saisons'?", [], "vivaldi"],
                ["Quel est la note la plus grave en musique? (sans compter Do)", [], "ré"],
                ["Quel est le nombre premier suivant après 7?", [], "11"],
                ["Quel est le seul nombre pair qui est aussi un nombre premier?", [], "2"],
                ["Quel est l'animal qui peut être confondu avec la grenouille mais qui a une peau plus rugueuse?", [], "crapaud"],
                ["Quel est l'animal que l'on n'aime jamais nourrir?", [], "moustique"],
                ["Quel mot est orthographié incorrectement dans tous les dictionnaires?", [], "incorrectement"],
                ["Un coq pond un œuf sur le toit. De quel côté tombe-t-il?", [], "aucun"],
                ["Trouver le nombre suivant dans la suite de nombres : 2, 3, 5, 7, 11, 13, ?", [], "17"],
                ["Quel est le plus grand désert chaud du monde?", [], "sahara"],
                ["(3+5×4)−2^3+10=?", [], "25"],
                ["Combien de vertèbres comporte la colonne vertébrale humaine?", [], "33"],
                ["Quel type de tissus relie les muscles aux os?", [], "tendons"],
                ["Quel organe filtre les déchets du sang?", [], "reins"],
                ["Quel est l'autre nom du gros intestin?", [], "côlon"],
                ["Où se trouve l'utérus?", [], "abdomen"],
                ["Comment appelle-t-on la petite boule de glace qui tombe parfois lors des orages?", [], "grêle"],
                ["Comment s'appelle la couche de l'atmosphère où se produisent les phénomènes météorologiques?", [], "troposphère"],
                ["Quel instrument mesure la vitesse du vent?", [], "anémomètre"],
                ["Quel phénomène se produit lorsqu'il y a une différence de pression d'air entre deux endroits?", [], "vent"],
            ];
            break;
        case "impossible" :
            $dataQ = [
                ["Comment s'appelle le tempo le plus rapide?", [], "presto"],
                ["Quel est le tempo moyen d'un morceau de tempo 'Allegro' en BPM?", [], "108-132"],
                ["Quel symbole musical représente un volume très doux?", [], "p"],
                ["Comment appelle-t-on les particules en suspension dans l'air qui contribuent à la formation des nuages?", [], "aérosols"],
                ["Qui a gagné la coupe du monde en 2022?", [], "argentine"],
                ["Quel unité est souvent utilisée pour mesurer la pression atmosphérique?", [], "hectopascal"],
                ["Comment s'appelle l'échelle utilisée pour mesurer l'intensité des tornades?", [], "fujita"],
                ["Quel est la température de congélation de l'eau en Fahrenheit?", [], "32"],
                ["Trouver le nombre suivant dans la suite de nombres : 6, 56, 1488, ?", [], "32512"],
                ["Quel appareil enregistre et mesure les tremblements de terre?", [], "sismograph"],
                ["Qui a peint 'La Riconoscenza della Repubblica Italiana a Napoleone'?", [], "giuseppe"],
                ["Combien de zéros dans le Gogol?", [], "100"],
                ["Quel est la capitale de Saint-Vincent-et-les-Grenadines?", [], "kingstown"],
                ["Quel est l'animal national du Canada?", [], "castor"],
                ["Comment s'appelle le quartier financier de Tokyo?", [], "marunouchi"],
                ["Quel ville américaine est surnommée 'La ville du vent'?", [], "chicago"],
                ["Quel ville est connue pour le plus grand nombre de gratte-ciels au monde? (écrire la réponse tout attaché)", [], "hongkong"],
                ["Quel est le plus petit os du corps humain?", [], "étrier"],
                ["Où se trouve le marteau dans le corps humain?", [], "oreille"],
                ["Quel est le seul os humain capable de se régénérer entièrement après une perte partielle?", [], "mandibule"],
                ["Combien de litres de sang le cœur pompe-t-il chaque jour en moyenne?", [], "7500"],
                ["Quel pourcentage de notre cerveau est constitué d'eau?", [], "75"],
                ["Quel est l'organe capable de se dilater jusqu'à 50 fois sa taille initiale?", [], "estomac"],
                ["Comment s'appelle l'os qui relie la hanche à la colonne vertébrale?", [], "sacrum"],
                ["Comment s'appelle nom du pigment qui donne à la peau sa couleur?", [], "mélanine"],
                ["Combien de nerfs crâniens se trouvent dans le corps humain?", [], "12"],
                ["Quel style de danse né à Cuba mélange des influences africaines et espagnoles?", [], "rumba"],
                ["Combien de positions de base des pieds existe-t-il dans le ballet classique?", [], "5"],
                ["Quel est le nom de la célèbre école de danse rattachée à l'Opéra de Paris?", [], "nanterre"],
                ["Quel danseuse est considérée comme la pionnière de la danse moderne?", [], "duncan"],
                ["Dans quelle ville célèbre le ballet 'Le Lac des cygnes' a-t-il été joué pour la première fois", [], "moscou"],
                ["Quel terme décrit une série de sauts exécutés avec les jambes écartées au ballet?", [], "sissonnes"],
                ["Combien de lettres compte l'alphabet grec classique?", [], "24"],
                ["Quel est la signification du charactère chinois '人' en italien?", [], "persona"],
                ["Quel est l'opérateur utilisé pour vérifier l'égalité en JavaScript sans tenir compte du type?", [], "=="],
                ["Quel est l'outil de gestion de version le plus utilisé dans le développement de logiciels?", [], "git"],
                ["En Python, quel mot-clé est utilisé pour définir une fonction?", [], "def"],
                ["Dans quel langage est écrit le noyau de Linux?", [], "c"],
                ["Quel langage de programmation a été développé par Bjarne Stroustrup?", [], "c++"],
                ["Quel est la durée d'un jour sur Neptune? (en heures)", [], "16"],
                ["Combien de galaxies composent le groupe local, auquel appartient la Voie lactée?", [], "54"],
                ["Quel est la température moyenne à la surface de la planète Vénus en Kelvin? (arrondi à l'unité)", [], "733"],
                ["Quel est le nom de l'astéroïde qui a causé l'extinction des dinosaures?", [], "chicxulub"],
                ["Quel est la durée d'une année sur Uranus? (en années terrestres)", [], "84"],
                ["Quel est le nom de la lune la plus éloignée de sa planète?", [], "neso"],
                ["Quel est le nom de l'astronome qui a formulé le modèle géocentrique de l'univers, largement accepté avant Copernic?", [], "ptolémée"],
                ["Quel est l'étoile la plus brilliante de la constellation d'Orion?", [], "rigel"],
                ["Quel est le plus grand arbre connu sur Terre, mesuré en volume total de bois?", [], "hyperion"],
                ["Quel est le nom de la première espèce de mammifère à avoir été clonée avec succès en 1996?", [], "mouton"],
                ["Comment s'appelle l'insecte qui peut supporter des radiations mortelles et survivre dans l'espace?", [], "tartigrade"],
                ["Comment s'appelle le supercontinent qui a existé il y a environ 335 à 175 millions d'années?", [], "pangée"],
                ["Comment s'appelle la roche sédimentaire composée principalement de grains de sable?", [], "grès"],
                ["Quel est le terme pour désigner un magma qui a refroidi à la surface terrestre?", [], "lave"],
                ["Quel est la traduction anglaise du mot lithuanien 'smegenys'?", [], "brain"],
                ["Combien d'éléments naturels existent dans le tableau périodique?", [], "92"],
                ["Quel est le terme pour désigner la division cellulaire des cellules somatiques?", [], "mitose"],
                ["Quel alphabet ancien est considéré comme le prédécesseur direct de l'alphabet grec?", [], "phénicien"],
                ["Quel alphabet comporte les lettres 'æ' et 'ø'?", [], "danois"],
                ["Quel lettre est la moins utilisée dans l'alphabet anglais?", [], "z"],
                ["Quel est le plus ancien alphabet utilisé dans la péninsule arabe?", [], "sabéen"],
                ["Quel est la couleur des yeux de tous les chatons à la naissance?", [], "bleu"],
                ["Combien de sons différents un chat peut-il produire pour communiquer?", [], "100"],
                ["Quel est le plus grand type de tortue d'eau douce domestique?", [], "trachémyde"],
                ["Comment se nomme la langue ancienne parlée par les Mayas et encore utilisée par certains groupes aujourd'hui?", [], "yucatèque"],
                ["Quel est le nom du mécanisme du corps qui arrête spontanément le saignement suite à une blessure?", [], "hémostase"],
                ["Comment se nomme l'effet qui cause le changement de fréquence des ondes sonores à cause de la vitesse relative de la source?", [], "doppler"],
                ["Quel terme désigne le point d'orgue d'un opéra?", [], "aria"],
                ["Quel est le nombre maximal de dimensions postulées par la théorie des cordes pour que ses équations soient cohérentes?", [], "11"],
                ["Quel mot de cinq lettres, en anglais, devient plus court lorsqu'on lui ajoute deux lettres?", [], "short"],
                ["Quel est le nom de l'ensemble qui explore la théorie mathématique explorant les possibilités infinies de fractales dans les nombres complexes?", [], "mandelbrot"],
                ["Si une rivière coule sans jamais se répéter, peut-on la traverser deux fois au même endroit?", [], "non"],
                ["Quel est le son d'une seule main qui applaudit?", [], "silence"],
                ["Si un arbre tombe dans une forêt sans personne pour l'entendre, fait-il du bruit?", [], "inconnu"],
                ["Si vous prenez le mot 'paradoxe' et en trouvez le contraire, existera-t-il encore?", [], "non"],
                ["Peut-on dire que quelque chose n'a jamais existé?", [], "non"],
                ["Une minute dans un trou noir dure combien de temps pour l'extérieur?", [], "infini"],
                ["La perfection peut-elle être imparfaite?", [], "oui"],
                ["Si une poule et demie pond un œuf et demi en un jour et demi, combien pondent trois poules en trois jours?", [], "6"],
                ["Que devient le paradoxe du bateau de Thésée?", [], "identité"],
                ["Quel est la moitié d'un infini?", [], "infini"],
                ["Combien de jours un esprit doit-il rester sur Terre avant de trouver la paix, selon la tradition chinoise?", [], "49"],
                ["Quel est le nombre considéré comme porte-malheur dans la culture asiatique?", [], "4"],
                ["Dans quelle ville américaine se trouve le célèbre 'Amityville Horror'?", [], "amityville"],
                ["Comment appelle-t-on une personne prétendant être capable de communiquer avec les morts?", [], "médium"],
                ["Dans la culture européenne, combien de jours après la mort une âme peut-elle revenir hanter son lieu de vie?", [], "3"],
                ["Comment s'appelle l'entité surnaturelle que certains croient responsable des cauchemars?", [], "mare"],
                ["Dans quelle ville l'histoire du 'Bazar du Diable' a-t-elle eu lieu?", [], "paris"],
                ["Quel est le nom du surnom donné à l'objet volant non identifié (OVNI)?", [], "soucoupe"],
                ["Selon certaines croyances indigènes, quel est le nombre d'esprits censés résider dans un corps humain?", [], "5"],
                ["Dans quelle ville a été signée la Déclaration d'Indépendance des États-Unis?", [], "philadelphie"],
                ["En quelle année a eu lieu la chute du Mur de Berlin?", [], "1989"],
                ["En quelle année l'Inde a-t-elle obtenu son indépendance du Royaume-Uni?", [], "1947"],
                ["Quel est le nom de la première civilisation à avoir utilisé l'écriture?", [], "sumérienne"],
                ["Quel est le nom du premier site de commerce en ligne fondé en 1994?", [], "amazon"],
                ["Quel est le nom du système d'exploitation utilisé dans la majorité des smartphones en Chine?", [], "harmonyos"],
                ["En quelle année a été fondée la société Tesla?", [], "2003"],
                ["Quel est le nom de la première entreprise à avoir développé une puce graphique pour les jeux vidéo?", [], "nvidia"],
                ["Quel est le nom du premier moteur de recherche sur Internet?", [], "archie"],
                ["Quel est le premier langage de programmation utilisé pour le développement de logiciels sur un ordinateur?", [], "fortran"],
                ["En quelle année a été fondée la société Apple?", [], "1976"],
            ];

            break;
    }

    $questions = [];

    foreach ($dataQ as $index => $q) {
        shuffle($q[1]);
        $question = new Question($q[0], $q[1], $q[2]);
        $questions[$index] = $question->toArray();
    }
    shuffle($questions);

    return $questions;

}